### ISSUE TITLE
undo options

### ISSUE THREAD

**Issue by yadav-anil92** [SteveBarnegren/SwiftChess#13]
I want to add undo options, guide me on how to do undo?

**Comment by SteveBarnegren** [comment]
Hi @yadav-anil92 

This isn't currently supported, but it shouldn't be too difficult to add undo functionality to SwiftChess. I think the best approach would be to save an array of the previous states of the board in `Game`. Before each move is made, the current board can be appended to that array. Then if you want to undo, you can just wind the board back to the previous state.

If you wanted to animate that, you might have to also (or only!) store the 'reverse' of the moves that were last made, so that they can be performed to reset the board to the previous state.

Does that help you out?

**Comment by yadav-anil92** [comment]
@SteveBarnegren 
Yes, I did the same but when user tap on undo I re-initialize game like
game = Game(dictionary: dictionary)
then re-add all pieces to board its work but difficult to animate the moves.

Could you please help me to animate the moves? or Can you give me some code hint to do that?

**Comment by SteveBarnegren** [comment]
I think you would probably need to store the last move that was made, so that you could then play a reverse animation when you undo it.

eg. if you player moves, from index `2` to index `10`, you can store that data. When the move is reversed, you should then be able to animate the player at `10` to index `2`.

You could either modify `SwiftChess.Game` to add that functionality, or store that information outside of the `Game`, and then use that to play back a reverse animation and also reinstate the game from a dictionary as you're doing now.
