### ISSUE TITLE
Some time moves not working.

### ISSUE THREAD

**Issue by anil004-dev** [SteveBarnegren/SwiftChess#15]
Moving g6 to e7 not working with Piece.PieceType.knight

Please help me

piece :Piece(type: SwiftChess.Piece.PieceType.knight, color: SwiftChess.Color.black, tag: Optional(0), hasMoved: false, canBeTakenByEnPassant: false, location: SwiftChess.BoardLocation(index: 0)), location: BoardLocation(index: 52)
Piece is unable to move to this location
![Simulator Screen Shot - iPhone 11 - 2019-10-17 at 12 40 07](https://user-images.githubusercontent.com/53460994/66985912-6d135b80-f0db-11e9-9b5b-fc7e5d79c706.png)

**Comment by SteveBarnegren** [comment]
Hi @anil004-dev, sorry for the delay in getting back to you!

I'm not sure exactly what the issue is here unfortunately. It's difficult for me to fix these sorts of issues from a screenshot because it would take be some time to try and recreate the scenario. If you still want me to look in to it then if you're able to create a failing unit test then I'll be able to fix it for you.

Thanks
